### ISSUE TITLE
How do we identify organizations?

### ISSUE THREAD

**Issue by jmandel** [AudaciousInquiry/fhir-saner#16]
When I see the BedGroup defining a reference to an Organization at:
![image](https://user-images.githubusercontent.com/313089/77547782-a4044f00-6e7b-11ea-982e-7651b31bdc92.png)

Why require reference.identifier, vs providing a reference to a FHIR resource that might contain not only an NPI, but other information too? For example, the information source sending Group data might also be sending Organization data, and could unambiguously refer to the correct Organization via reference.reference, rather than reference.identifier. (Imagine a scenario where the receiving system already had a bunch of data imported from different sources, and had multiple Organization resources all with a single NPI -- this gets messy). If *only* the NPI is known, we can always provide a contained resource (though I suspect that's not super common).

Or, backing way up: why do we need a managingEntity here at all? If we already have a Location (pointed to through the "Location.partOf" characteristic, that location can provide all the necessary geographical details, and if desired can point to an organization too.

**Comment by keithboone** [comment]
This is likely Measure specific.
