### ISSUE TITLE
User Story: Find a number of beds

### ISSUE THREAD

**Issue by keithboone** [AudaciousInquiry/fhir-saner#24]
Scenario: Find a number of beds

Find 10 (or some other number) of beds for treatment of a newly discovered outbreak in a community.

This story is inspired in part by the Life Care Center crisis in Kirkland, WA

As an [Emergency Responder](../wiki/Persona#emergency-responder) or [Public Health Official](../wiki/Persona#public-health-official)
I want to find one or more facilities with a number of beds
So that I can I can route patients to treatment and emergency responders 
for followup testing.

Given A {Location} and a {Quantity} of beds matching {FilterCriteria}
When I look at {a map}
Then I can find nearby {Facilities} which have beds meeting {FilterCriteria}
And I can find nearby {Facilities} which have {TestingResources}

**Comment by JohnMoehrke** [comment]
How is this different than step #7 and #8 of Use-Case 1 "Collecting Hospital and Ventilator Measures"?

**Comment by JohnMoehrke** [comment]
Is this a query on Measure or MeasureReport?  Seems this might be the CDC MeasureReport? (i.e. Not the FMEA report?)

http://build.fhir.org/ig/HL7/fhir-saner/Measure-CDCPatientImpactAndHospitalCapacity.json.html

Which are the minimal query parameters?

Many examples for CDC Patient have an element in Measure.measure that doesn't appear to exist in FHIR Measure.
 "measure" : "http://hl7.org/fhir/us/saner/Measure/CDCPatientImpactAndHospitalCapacity",

How do I search for Measure resources on bed availability?

looking at Measure. It would seem .topic would be a welldefined value for CDC Bed topic

or Measure.type be a well defined value for CDC Bed topic

the structure definition seems to have a well defined value for the Measure.group.code; but this is not a querable 

seems I would want to request Measure of a given type... then look in the .group for the values for beds???

**Comment by keithboone** [comment]
GET [base]/MeasureReport?measure=_uri_&period=gt_start_&period=lt_end_&subject=_location_
Find all MeasureReport resources for the measure specified by uri, for the specified period and location.

GET [base]/MeasureReport?code=#code&period=gt_start_&period=lt_end_&subject=_location_
Find all MeasureReport resources using the specified code, for the specified period and location.

**Comment by awatson1978** [comment]
So, I managed to render out the `numBeds` measureScore to a marker on a map.  

![Symptomatic-SANER-Chicago-EpicData](https://user-images.githubusercontent.com/675910/83347550-5d075f80-a2eb-11ea-8376-fe37c6049480.jpg)

By itself, I don't think `numBeds` is addressing the concern in the user story.  It also needs the census data, so the relative capacities can be calculated.
