### ISSUE TITLE
User Story: Trend Bed Usage for a Region

### ISSUE THREAD

**Issue by keithboone** [AudaciousInquiry/fhir-saner#25]
Feature: Trend Bed Usage for a Region

As a [Public Health Official](../wiki/Persona#public-health-official)
I want to be able to see trends about utilization of beds or other resources
So that I can 
+ investigate reported concerns about facilities or regions
+ take pre-emptive action to alleviate shortages
+ be aware of facilities or regions at risk
+ avoid routing patients to a specific region or facility
+ route patients to other regions or facilities for treatment that have capacity

Background: Region of Concern
Given A {Region} or {Facility}

Scenario: Routine review
When I perform my routine review of a {Region} or {Facility}
Then I can identify the risk level of a {Region} or {Facility} due to shortage of {Resources}

Scenario: Triggered Review
When  a concern triggers review of a {Region} or {Facility}
Then I can identify the risk level of a {Region} or {Facility} based on {Resource} availability

**Comment by awatson1978** [comment]
I managed to put together the following trend graph for the number of MeasureReports collected per day.  I didn't unbox the MeasureReports to graph the contents of `numBeds`, but it's something that could be done easily enough going forward.  But even just trending the participation rate might give a public health official some insight on whether a facility has fallen off the map (i.e. they didn't report in).  

![Symptomatic-SANER-Leaderboard-Dashboard](https://user-images.githubusercontent.com/675910/83347736-a0ae9900-a2ec-11ea-88b7-5be75e4b2ee6.png)

Personally, I think this item would be better entitled as `Trend Bed Usage for an Organization`.
