### ISSUE TITLE
Update Cerner entries in bed reporting analysis

### ISSUE THREAD

**Issue by jmandel** [AudaciousInquiry/fhir-saner#30]
For https://github.com/AudaciousInquiry/saner-ig/wiki/Bed-Classification, update Cerner column to reflect current practices

**Comment by keithboone** [comment]
We are changing how we address this.  Instead of producing measures as part of the guide, we are going to describe the process and provide example measures using CDC and FEMA guidelines, so that we can avoid having to follow a moving target.
