### ISSUE TITLE
Reach out to Logica to get Assistance with Value Sets

### ISSUE THREAD

**Issue by keithboone** [AudaciousInquiry/fhir-saner#46]
Reach out to Stan Huff to invite him and Logica to contribute Value Set content into Measure stuff for SANER.

**Comment by DavidPyke** [comment]
Stan's reply: The LOINC codes for orders and results are on a special page on the loinc.org website.  Logica has created FHIR profiles for all of the specific lab results and these are posted at https://covid-19-ig.logicahealth.org/index.html.  Our result models are consistent with models that we have reviewed with CIMI and Orders and Observation Work Groups. We have not made order profiles as far as I know.  Would you like to work together on the order profiles?  Susan Matney and Nathan Davis are the folks that are leading the efforts in this area.

**Comment by DavidPyke** [comment]
THe positive-negative set is: https://covid-19-ig.logicahealth.org/ValueSet-covid19-pos-neg-vs.html
