### ISSUE TITLE
HL7 Administration

### ISSUE THREAD

**Issue by keithboone** [AudaciousInquiry/fhir-saner#48]
since SANER is now officially and HL7 project, there are few things that the project team needs to start doing because of HL7’s openness requirements. This includes announcing the project meetings on the sponsor/co-sponsor list servers, getting the project minutes up on a HL7 Confluence page under the PA space. Setting up the thrice weekly calls on the HL7 Conference Call calendar will help address the announcement aspect, since it can automatically notify the necessary lists, but pushing out agendas will take a little extra effort.. Using the current ringcentral web-conference information is fine, but these calls do need to be announced to HL7 membership.
 
I’m not sure what level of project oversight PA expects to perform for this project, but obviously, major decisions around balloting, major changes in scope of the project, establishing Connectathon tracks, etc. need to be run through the work group.

**Comment by DavidPyke** [comment]
Conflunence page created: https://confluence.hl7.org/x/tIrGB
Minutes copied into subpages (missing for April 6 and April 8)
Calls registered into HL7 Conference Call system

**Comment by DavidPyke** [comment]
complete
