### ISSUE TITLE
Feedback via the Hl7 Confluence page

### ISSUE THREAD

**Issue by DavidPyke** [AudaciousInquiry/fhir-saner#49]
Andrea Pitkus gave this feedback as a comment to the minutes of Apr.8

Regarding  Lab Order and Result Codes, please see the LOINC PreRlease COVID-19  terms, which would be used to map the order and result from the  performing lab:  https://loinc.org/prerelease/ 
 
Regarding  Result Values, the performing lab should be mapping to the SNOMED CT  qualifier value for OBX5, per the ELR guide, required by law in the US.   Clinical laboratories are advised by CDC  NOT to attempt viral isolation (method which would be used to identify  the virus/organism, so folks wouldn't be reporting SCT organism codes if  not identifying.)  Looking at LOINCs, all the result values are either  numeric (which would be uncoded by terminology, but include UCUM units),  or Qualitative (Presence, Detected, etc).   The performing lab must  report out the rest result value indicated on the manufacturer package  insert.

**Comment by keithboone** [comment]
Where we create sample value sets (e.g., used to evaluate a measure),  we need to ensure that we just use result codes (order and observation/both, or observation only codes), not order codes for the value set.

In other words, use the value sets for the purposes for which they were designed.

Right now we don't have value sets for automating the computation of measures, but will use this advice in the future when such automation is implemented.
