### ISSUE TITLE
Patient List for Contact Tracing

### ISSUE THREAD

**Issue by DavidPyke** [AudaciousInquiry/fhir-saner#60]
As a Public Health Official I want to know the list of patients who have tested positive so I can do contact tracking.  If I can get the date that the patient first showed symptoms, I can backtrack and begin to determine who they may have been in contact with while asymptomatic.  Date of test may be sufficient as that is a minimal date to start back tracing from.

Given {facility} supporting inpatient non-acute care
When there are {COVID+ Patients}
Then the {list of Patients with positive test result} and ({date of first symptom} OR  {date of test}) is reported

**Comment by keithboone** [comment]
@DavidPyke How would the workflow work for this?

Would public health request a contact list based on a summary report that had been previous communicated by the facility?  Where and how would that request be submitted?  Today, just the numbers are being reported, and for most cases, there's a separate way of handling case reporting for covid+ patients.

We should ask Austin to review this user story.  It may duplicate existing processes (e.g., e-Case Reporting).

**Comment by keithboone** [comment]
Outside of scope for this release.
