### ISSUE TITLE
Allow servers to require search parameters

### ISSUE THREAD

**Issue by michaeldonnelly** [AudaciousInquiry/fhir-saner#74]
If a client performs a MeasureReport search that doesn't include an _id parameter:

- The server MAY require that a **measure** parameter is present.
- The server MAY require that a **period** parameter is present.
- The server MAY require that a **subject** parameter is present

**Comment by keithboone** [comment]
Absolute should say what Measure you want (1..n)
For period, in a lot of cases, your are going to get someone who wants yesterday's day.
Being able to specify a range of period. (1..2)
Subject shouldn't be required 
Reporter might be desirable for diagnostics

These should be the minimum requirements for what the server supports, the server can go beyond that.  
Servers **shall** report on what must be used to interact with the server ( see [US Core IG](https://www.hl7.org/fhir/us/core/general-guidance.html#search-for-servers-requiring-status
))
Clarify certain optional features ... if you are going to support this, do it this way.

**Comment by michaeldonnelly** [comment]
- The client SHOULD provide the **measure** parameter (1..*).
- The server MAY have business rules that require the **measure** parameter (1..*).
- The server MAY have business rules that require the client to specify a range in the **period** parameter (1..2).
- If the server has business rules requiring parameters or sets of parameters, when rejecting a request the server
  - SHALL return an http `400` status
  - SHALL return an OperationOutcome specifying what parameter(s) must be present

**Comment by keithboone** [comment]
Resolved
