### ISSUE TITLE
Should SANER require conformance to specific measure definitions

### ISSUE THREAD

**Issue by JohnMoehrke** [AudaciousInquiry/fhir-saner#81]
given that SANER has been using CDC and FEMA to help with the modeling, and that most of the testing has been focused on those two measure definitions.... Should SANER 
a) be totally agnostic, thus moving CDC and FEMA measure definitions out-of-scope completely
b) treat the given CDC and FEMA measures as known measure definitions that are simply known about but not tested for
c) test for compliance to CDC or FEMA measure definition when a MeasureDefinition says that it is of those types

If (c) then how do we support expanding measure definitions to others? Are each future measure definition brought in as a sub part of the SANER IG?

**Comment by JohnMoehrke** [comment]
Is there precedent in Questionnaire IGs? There likely has been more lessons-learned there.

**Comment by jmandel** [comment]
I think we might just try to solve this as the highest level by letting services say things like:
1. I support SANER core functionality
2. I support SANER with the CDC modules v2020-05-10
3. I support SANER with the FEMA modules v2020-05-10

To get this behavior, we can define a list of `CapabilityStatement` canonical URLs like:

1. `http://hl7.org/fhir/uv/fhir-saner/CapabilityStatement/core-capabilities`
2. `http://hl7.org/fhir/uv/fhir-saner/CapabilityStatement/cdc-modules|2020-05-10`
3. `http://hl7.org/fhir/uv/fhir-saner/CapabilityStatement/fema-modules|2020-05-10`

And the a system points to these URLs to *express the fact they support these capabilites*, like:

```
{
  "resourceType": "CapabilityStatement",
  "instantiates": [
    "http://hl7.org/fhir/uv/fhir-saner/CapabilityStatement/core-capabilities",
    "http://hl7.org/fhir/uv/fhir-saner/CapabilityStatement/fema-modules|2020-05-10",
    "http://hl7.org/fhir/uv/fhir-saner/CapabilityStatement/cdc-modules|2020-05-10"
  ]
}
```

For an example of where we take this approach, see: https://hl7.org/fhir/uv/bulkdata/operations/index.html

**Comment by keithboone** [comment]
Implementations would conform to profiles of Measure and MeasureReport, but not specific Measures for conformance to the Universal Guide.
