### ISSUE TITLE
Recommend the number of entries that servers return by default before paging

### ISSUE THREAD

**Issue by michaeldonnelly** [AudaciousInquiry/fhir-saner#84]
A large bundle of MeasureReports can be large and can take a long time to load.  (1000 MeasureReports from our system is ~5MB and takes around 30 seconds.)  Clients can control this with the `_count` search parameter, but many don't know that.  

Potential issues
- If it's been 30 seconds, how does a client know the server is still working?  When should the client give up?
- Some clients will run out of resources (e.g. memory) processing too many entries at once.  

Should we have a recommended default for how many entries servers return if the client doesn't specify a `_count`?

**Comment by michaeldonnelly** [comment]
Here are some examples of how long it takes and how big it is.

Entries | Response Time (seconds) | Size (MB)
------------ | ------------- | -------------
10 | 0.48 | 0.05
50 | 1.70 | 0.27
100 | 3.73 | 0.53
200 | 7.21 | 1.04
250 | 8.05 | 1.30
500 | 16.15 | 2.60
1000 | 33.63 | 5.19
 
All of these searches start at the same point and are for warm data.

**Comment by michaeldonnelly** [comment]
Other systems may be different, but at least with Epic's, the response time and size scale linearly.  (Except for the first sample above; anything with more than that, the overhead vanishes into the cost per MeasureReport.)

**Comment by keithboone** [comment]
I generally set default count values for clinical information systems to around 20 (maybe higher for labs).

**Comment by michaeldonnelly** [comment]
3 -5 second response time sounds like a reasonable bar.  Assuming a Measure that's reported on daily, 100 entries would get:
- A single location for more than three months
- Every hospital in Rhode Island for a week and a half
- Every hospital in the Chicago area for two days

And that'd just be a default.  There's nothing to stop the server from allowing the client to specify a **higher** `_count` than the default.

**Comment by michaeldonnelly** [comment]
Does anyone have examples where 100 entries would take more than 5 seconds?  What about examples where you could get significantly more than 100 entries in 3 seconds?
