### ISSUE TITLE
add sample randomization code to new implementation materials folder

### ISSUE THREAD

**Issue by JohnMoehrke** [AudaciousInquiry/fhir-saner#90]
Decided on SANER call 5/22/2020
ACTION: Keith to create a folder in the HL7 SANER IG github repository for implementation materials and sample code snippits
ACTION: Michael to add his C++, and MUMPS code files to that folder
ACTION: John to write high-level pseudocode to explain the concept with links to the code in the folder

_Originally posted by @JohnMoehrke in https://github.com/AudaciousInquiry/fhir-saner/issues/85#issuecomment-632795048_

**Comment by michaeldonnelly** [comment]
Waiting on https://github.com/AudaciousInquiry/fhir-saner/issues/89
