### ISSUE TITLE
Add reference to Dartmouth Atlas for HSA, HRR, PCSA

### ISSUE THREAD

**Issue by keithboone** [AudaciousInquiry/fhir-saner#94]
See https://confluence.hl7.org/display/TA/Dartmouth+Atlas+of+Health+Care

These are references to regions that might be useful in roll-up reporting.

**Comment by awatson1978** [comment]
Like so:

![Symptomatic-SANER-Choropleth-EasterCentralTimeZones](https://user-images.githubusercontent.com/675910/83320175-93b97900-a20a-11ea-8e3a-c439e64dcd74.png)

**Comment by keithboone** [comment]
Done
